//go:build ignore

// gen.go writes notice.txt, the embedded provenance string. CI passes the release
// metadata via EMBED_VERSION, EMBED_COMMIT, and EMBED_DATE; local runs use dev defaults.
// The file is never committed (.gitignored); it exists only in the release artifacts.
package main

import (
	"fmt"
	"os"
)

func main() {
	version := env("EMBED_VERSION", "v0.0.0-dev")
	commit := env("EMBED_COMMIT", "unknown")
	date := env("EMBED_DATE", "unknown")
	s := fmt.Sprintf("This file was generated by CI on %s as part of the release pipeline "+
		"for version %s (%s). It is not present in the source code, only in the release "+
		"artifacts.\n", date, version, commit)
	if err := os.WriteFile("notice.txt", []byte(s), 0o644); err != nil {
		panic(err)
	}
}

func env(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
